services:
  bot:
    image: node:20-alpine
    working_dir: /app
    env_file: .env
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/gathercord?schema=public"
      SHADOW_DATABASE_URL: "postgresql://postgres:postgres@db_shadow:5432/postgres?schema=public"
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: "true" # reliable file watching in containers
    depends_on:
      db:
        condition: service_healthy
      db_shadow:
        condition: service_healthy
    command: >
      sh -c "npm ci && npx prisma generate && npx prisma migrate deploy && npm run dev"
    volumes:
      - ./apps/bot:/app
      - /app/node_modules
    ports:
      - "3000:3000" # drop if not needed
