services:
  bot:
    image: node:20-slim
    working_dir: /workspace
    env_file: .env
    environment:
      NODE_ENV: development
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/gathercord?schema=public"
      SHADOW_DATABASE_URL: "postgresql://postgres:postgres@db_shadow:5432/postgres?schema=public"
      CHOKIDAR_USEPOLLING: "true"
    depends_on:
      db: { condition: service_healthy }
      db_shadow: { condition: service_healthy }
    command: >
      sh -c " apt-get update && apt-get install -y --no-install-recommends openssl ca-certificates && rm -rf /var/lib/apt/lists/* && npm ci && npx prisma generate --schema apps/bot/prisma/schema.prisma && npx prisma migrate deploy --schema apps/bot/prisma/schema.prisma && npm run -w apps/bot dev "
    volumes:
      - ./:/workspace
      - /workspace/node_modules
    ports:
      - "3000:3000"
