services:
  bot:
    build:
      context: .
      dockerfile: apps/bot/Dockerfile
    env_file: .env
    environment:
      NODE_ENV: production
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
      DATABASE_URL: postgresql://postgres:postgres@db:5432/bot
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gathercord
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d gathercord" ]
      interval: 3s
      timeout: 3s
      retries: 20
    volumes:
      - db_data:/var/lib/postgresql/data
  db_shadow:
    image: postgres:16-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gathercord_shadow
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d gathercord" ]
      interval: 3s
      timeout: 3s
      retries: 20
    volumes:
      - db_shadow_data:/var/lib/postgresql/data

volumes:
  db_data:
  db_shadow_data:
